from __future__ import annotations

EXPORT_COLUMNS_V1 = [
    "file_name",
    "merchant",
    "issue_date",
    "total_amount_gross",
    "currency",
    "invoice_number",
    "tax_number",
    "invoice_no",
    "tax_id",
    "trace_id",
    "sha256",
    "status",
    "error_code",
    "error_message",
    "warnings_count",
    "warnings_json",
    "parser_version",
    "retry_key",
    "doc_id",
    "doc_type",
    "template_id",
    "subtotal_amount_net",
    "tax_amount",
    "tax_rate",
    "category",
    "anomaly_count",
    "anomaly_codes",
    "confidence_overall",
    "source_file",
    "expense_batch_id",
]
